#!/usr/bin/env bash

_is_it_first()
{
  local node; node="$1"; shift
  local first; first=1
  if [ "${node:(-1)}" = 1 ]; then
    first=0
  fi
  return $first
}

_am_i_master()
{
  _is_it_first "${HOSTNAME}"
}

_get_nodes_addresses()
{
  local addresses;
  while IFS='' read -r a; do addresses+=("$a"); done < <(vmtoolsd --cmd "info-get guestinfo.appdata" | base64 -d | jq -r .vms[].net[].address)
  [ -z "${addresses[*]}" ] && fatal "Could not get nodes addresses"
  echo "${addresses[*]}"
}

_update_host_file()
{
  local hostname
  echo "# azcloud-apps" >> /etc/hosts
  for node in $(_get_nodes_addresses); do
    hostname="$(_run_on_node "$node" hostname -s)"
    echo "$node" "$hostname" "${hostname%%-*}" >> /etc/hosts
  done
}

_run_on_node()
{
  local node; node="$1"; shift
  local comm; comm="$*"
  ssh=();ssh=(ssh)
  ssh+=("-o ControlPath=~/.ssh/cm-%r@%h:%p")
  ssh+=("-o ControlMaster=auto")
  ssh+=("-o ControlPersist=10m")
  ssh+=("-o BatchMode=yes")
  ssh+=("-o PreferredAuthentications=publickey")
  ssh+=("-o PubkeyAuthentication=yes")
  ssh+=("-o StrictHostKeyChecking=no")
  ssh+=(root@"$node" -t "$comm")
  "${ssh[@]}"
}



