#!/usr/bin/env bash

install_and_setup_postgresql()
{
  _setup_pgsql_storage
  _install_and_setup_pgsql
  _setup_firewall_and_selinux

  if _am_i_master; then
    _setup_pgsql_master
  fi
}

general_prepare_nodes()
{
  _install_deps
  _install_avahi_centos
  _update_host_file 
}

azapps_databases_postgresql_master_slave()
{
  export HTTP_PROXY="$PROXY"
  export HTTPS_PROXY="$PROXY"
  export http_proxy="$PROXY"
  export https_proxy="$PROXY"

  general_prepare_nodes
  install_and_setup_postgresql
}
