#!/usr/bin/env bash

load_module()
{
  local app_path; app_path="$1"
  # shellcheck disable=SC2044
  for module in $(find "$app_path" -type f ! -name \*.sh\*); do
    # shellcheck disable=SC1090
    source "$module"
  done
}

main()
{
  case "$1" in
    install)
      AZCLOUD_APPS_MODE=install
      export AZCLOUD_APPS_MODE
      AZCLOUD_APPS_HOME=/var/lib/azin
      export AZCLOUD_APPS_HOME
      shift
      deploy "$@" ;;
    *)
      deploy "$@" ;;
  esac
}

deploy()
{
  set -x
  local app_path app_dir app_proxy run_module

  app_path="$1"; [ -z "$app_path" ] && { echo "app not found"; exit 1; }
  #app_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >& /dev/null && pwd )"
  #app_dir="${app_dir}/azcloud_apps"
  app_dir=$AZCLOUD_APPS_HOME
  load_module "${app_dir}"/modules/_variables
  load_module "${app_dir}"/modules/_functions

  if [ "$AZCLOUD_APPS_MODE" = deploy ]; then
    app_proxy="$(cat "$app_dir"/.proxy)"
    export PROXY="${app_proxy}"
    set_proxy
  fi

  AZCLOUD_APPS_DISTR="$(get_distribution_name)"
  export AZCLOUD_APPS_DISTR
  [ -z "$AZCLOUD_APPS_DISTR" ] && fatal "Could not detect distribution name"

  AZCLOUD_APPS_HOME="$app_dir"
  export AZCLOUD_APPS_HOME

  setup_dependencies || fatal "Could not setup dependencies"

  load_module "${app_dir}"/modules/"${app_path}"
  run_module=${app_path////_}; run_module=${run_module//+/_}

  if [ "$AZCLOUD_APPS_MODE" = deploy ]; then
    # read APPS.CONFIG in YAML and reexport
    variables_to_export=()
    while IFS='' read -r var; do
      export "${var?}"
      variables_to_export+=("${var}")
    done <<< "$(setup_module_variables "${run_module}")"

    for var in "${variables_to_export[@]}"; do
      while read -r dep_var; do
        eval "${dep_var}"
        export "${dep_var%%=*}"
      done <<< "$(grep "${var%%=*}" "${AZCLOUD_APPS_HOME}"/modules/_variables/"${run_module}" | grep -v ^"${var%%=*}")"
    done
  fi

  # read INCLUDE
  while read -r module; do
    load_module "${app_dir}"/modules/"$module"
  done <<< "$(grep -Irh "^# *INCLUDE:" "${app_dir}"/modules | awk -F: '{print $NF}' | tr ' ' '\n' | sort -u | sed '/^$/d')"
  
  azapps_"$run_module" >> "$AZCLOUD_APPS_HOME"/app.log 2>&1
}
