#!/usr/bin/env bash

_setup_nextcloud_config()
{
  su - "$AZCLOUD_APPS_NEXTCLOUD_WEBSERVER_USER" -s /bin/bash -c \
  "cd '$AZCLOUD_APPS_NEXTCLOUD_HOME' && \
   php occ  maintenance:install \
     --database '$AZCLOUD_APPS_NEXTCLOUD_CONFIG_DATABASE' \
     --database-name '$AZCLOUD_APPS_NEXTCLOUD_DATABASE_NAME' \
     --database-user '$AZCLOUD_APPS_NEXTCLOUD_DATABASE_USERNAME' \
     --database-pass '$AZCLOUD_APPS_NEXTCLOUD_DATABASE_PASSWORD'
     --admin-user '$AZCLOUD_APPS_NEXTCLOUD_ADMIN_USERNAME' \
     --admin-pass '$AZCLOUD_APPS_NEXTCLOUD_ADMIN_PASSWORD'
  "
  sed -i "/overwrite.cli.url/a 'overwriteprotocol' => '$AZCLOUD_APPS_NEXTCLOUD_CONFIG_OVERWRITE_PROTOCOL',"  "$AZCLOUD_APPS_NEXTCLOUD_CONFIG_FILE"
}

