#!/usr/bin/env bash

_setup_nextcloud_config()
{
  su - "$AZCLOUD_APPS_NEXTCLOUD_WEBSERVER_USER" -s /bin/bash -c \
  "cd '$AZCLOUD_APPS_NEXTCLOUD_HOME' && \
   php occ  maintenance:install \
     --database '$AZCLOUD_APPS_NEXTCLOUD_CONFIG_DATABASE' \
     --database-name '$AZCLOUD_APPS_NEXTCLOUD_DATABASE_NAME' \
     --database-user '$AZCLOUD_APPS_NEXTCLOUD_DATABASE_USERNAME' \
     --database-pass '$AZCLOUD_APPS_NEXTCLOUD_DATABASE_PASSWORD' \
     --admin-user '$AZCLOUD_APPS_NEXTCLOUD_ADMIN_USERNAME' \
     --admin-pass '$AZCLOUD_APPS_NEXTCLOUD_ADMIN_PASSWORD'
  "
  # set trusted domain, override protocol and allow_local_remote_servers ('host violates local access rules' error)
  # when adding host/port for antivirus.
  su - "$AZCLOUD_APPS_NEXTCLOUD_WEBSERVER_USER" -s /bin/bash -c \
  "cd '$AZCLOUD_APPS_NEXTCLOUD_HOME' && \
   php occ config:system:set trusted_domains 1 --value='*'
   php occ config:system:set overwriteprotocol --value='$AZCLOUD_APPS_NEXTCLOUD_CONFIG_OVERWRITE_PROTOCOL'
   php occ config:system:set allow_local_remote_servers --value='true'
  "
}

