#!/usr/bin/env bash

_install_and_setup_nextcloud_centos()
{
  yum -y install epel-release yum-utils
  yum -y install "$AZCLOUD_APPS_NEXTCLOUD_REMI_REPO"
  yum-config-manager --disable "$AZCLOUD_APPS_NEXTCLOUD_REMI_PHP_DISABLE"
  yum-config-manager --enable "$AZCLOUD_APPS_NEXTCLOUD_REMI_PHP_ENABLE"
  # shellcheck disable=SC2086
  yum -y install ${AZCLOUD_APPS_NEXTCLOUD_REQ[*]}

  yum -y install mariadb-server
  systemctl enable --now mariadb
  _setup_"$AZCLOUD_APPS_NEXTCLOUD_DATABASE"_nextcloud || fatal "Could not setup database for nextcloud"
  _setup_"$AZCLOUD_APPS_NEXTCLOUD_WEBSERVER"_nextcloud || fatal "Could not setup webserver for nextcloud"
}

_start_nextcloud_centos()
{
  systemctl enable --now "$AZCLOUD_APPS_NEXTCLOUD_WEBSERVER"
  systemctl restart "$AZCLOUD_APPS_NEXTCLOUD_WEBSERVER"
}
