#!/usr/bin/env bash

setup_gluster_storage()
{
  local app_storage_name; app_storage_name="$1"; shift
  setup_app_storage "$app_storage_name" || fatal "Could not setup app storage"
  mkdir -p "$AZCLOUD_APPS_STORAGE"/brick
}
