#!/usr/bin/env bash

install_general()
{
  :
}

install_and_setup_keepalived()
{
  :
}

install_and_setup_haproxy()
{
  :
}


main()
{
  export HTTP_PROXY=$PROXY
  export HTTPS_PROXY=$PROXY
  export http_proxy=$PROXY
  export https_proxy=$PROXY

  install_and_setup_keepalived
  install_and_setup_haproxy
}
