#!/usr/bin/env bash

azapps_storages_filesystem_nfs4()
{
  AZCLOUD_APPS_STORAGE="/var/lib/nfs4"
  export AZCLOUD_APPS_STORAGE

  PROXY="$(get_proxy)"
  export PROXY
  set_proxy

  NET="$(_get_default_network)"
  
  setup_firewall_and_selinux '2049' 'selinux:permissive' "$NET" \
    && stage_finished setup_firewall_and_selinux
  update_host_file \
    && stage_finished update_host_file
  setup_app_storage 'nfs4' \
    && stage_finished setup_app_storage 
  install_and_setup_nfs4 \
    && stage_finished install_and_setup_nfs4
}
  
