#!/usr/bin/env bash

_get_haproxy_config()
{
  local haproxy_config
  haproxy_config="$(vmtoolsd --cmd "info-get guestinfo.appdata" | base64 -d | jq -r .apps.config)"
  _throw_error "$haproxy_config"
  echo "$haproxy_config"
}

_get_haproxy_port()
{
  local port 
  port="$(_get_haproxy_config | jq -r .port)"
  _throw_error "$port"
  echo "$port"
}

_get_haproxy_mode()
{
  local mode
  mode="$(_get_haproxy_config | jq -r .mode)"
  _throw_error "$mode"
  echo "$mode"
}

_get_haproxy_balance()
{
  local balance
  balance="$(_get_haproxy_config | jq -r .balance)"
  _throw_error "$balance"
  echo "$balance"
}

_get_haproxy_vip()
{
  local vip
  vip="$(_get_haproxy_config | jq -r .vip)"
  echo "$vip"
}

_get_haproxy_servers()
{
  local raw_servers servers
  raw_servers="$(_get_haproxy_config | jq -r .servers)"
  IFS=',' read -ra servers <<< "$raw_servers"
  echo "${servers[@]}"
}

_install_and_setup_haproxy()
{
  local port; port="$(_get_haproxy_port)"
  local mode; mode="$(_get_haproxy_mode)"
  local balance; balance="$(_get_haproxy_balance)"
  local vip; vip="$(_get_haproxy_vip)"
  local servers; servers=($(_get_haproxy_servers))
  
  yum -y install haproxy
}

