#!/usr/bin/env bash


general_prepare_nodes()
{
  _update_host_file
}

install_and_setup_gluster()
{
  _setup_firewall_and_selinux
  _setup_gluster_storage
  _install_and_setup_gluster
}

azapps_storages_filesystem_gluster()
{
  export HTTP_PROXY="$PROXY"
  export HTTPS_PROXY="$PROXY"
  export http_proxy="$PROXY"
  export https_proxy="$PROXY"

  general_prepare_nodes
  install_and_setup_gluster
}
