#!/usr/bin/env bash

azapps_docker()
{
  if [ -z "$AZCLOUD_APPS_STORAGE" ]; then
    AZCLOUD_APPS_STORAGE="/var/lib/docker"
    export AZCLOUD_APPS_STORAGE
  fi

  PROXY="$(get_proxy)"
  export PROXY
  set_proxy
 
  setup_app_storage 'docker' \
    && stage_finished setup_app_storage
  setup_firewall_and_selinux '' 'selinux:permissive' \
    && stage_finished setup_firewall_and_selinux
  _install_docker_"$AZCLOUD_APPS_DISTR" \
    && stage_finished install_docker
  _install_docker_compose \
    && stage_finished install_docker_compose
  _setup_users_to_use_docker \
    && stage_finished setup_users_to_use_docker
  _start_docker \
    && stage_finished start_docker
}

