#!/usr/bin/env bash

_install_docker()
{
  # old one, no version control
  #curl -fsSL "$AZCLOUD_APPS_DOCKER_URL" | sh

  # new, with version control
  yum install -y yum-utils device-mapper-persistent-data lvm2
  yum-config-manager --add-repo "$AZCLOUD_APPS_DOCKER_REPO"
  yum install -y \
    containerd.io-"$AZCLOUD_APPS_DOCKER_CONTAINERD_VERSION" \
    docker-ce-"$AZCLOUD_APPS_DOCKER_VERSION" \
    docker-ce-cli-"$AZCLOUD_APPS_DOCKER_VERSION"
}

_install_docker_compose()
{
  local docker_compose_bin
  local docker_compose_url
  docker_compose_url="${AZCLOUD_APPS_DOCKER_COMPOSE_URL}/docker-compose-$(uname -s)-$(uname -m)"
  docker_compose_bin="/usr/local/bin/docker-compose"

  curl -L "$docker_compose_url" -o "$docker_compose_bin"
  chmod +x "$docker_compose_bin"
  ln -s "$docker_compose_bin" "${docker_compose_bin/local\//}"
}

_setup_users_to_use_docker()
{
  while IFS='' read -r user
  do 
    if [ "${user##*:}" -ge 1000 ]; then
      usermod -aG docker "${user%%:*}"
    fi
  done <<< "$(cut -d: -f1,3 /etc/passwd | sort -n -t: -k2,2)"
}

_start_docker()
{
  systemctl enable --now docker
}


