#!/usr/bin/env bash

azapps_storages_block_minio()
{
  export HTTP_PROXY="$PROXY"
  export HTTPS_PROXY="$PROXY"
  export http_proxy="$PROXY"
  export https_proxy="$PROXY"

  export MINIO_STORAGE="/minio/data" 
  _install_and_run_minio
}
