#!/usr/bin/env bash

_setup_firewall_and_selinux()
{
  if systemctl is-active firewalld | grep -q active; then
    firewall-cmd --permanent --zone=public --add-port="$MINIO_PORT"/tcp
  elif command -v iptables >& /dev/null; then
    iptables -I INPUT -p tcp --dport "$MINIO_PORT" -m comment --comment 'added by azcloud-apps' -m state --state NEW -j ACCEPT
 fi

  # set domain to permissive mode
  semanage permissive -a mysqld_t
}

_setup_minio_storage()
{
  local storage_vol; storage_vol="minio"
  local storage_group; storage_group="${storage_vol}_storage"
  local storage_dev; storage_dev="/dev/${storage_group}/${storage_vol}"

  [ -z "$MINIO_STORAGE" ] && fatal "MINIO_STORAGE not defined"

  mkdir -p "$MINIO_STORAGE"

  while IFS='' read -r a; do disks+=("$a"); done < <(lsblk | grep 'sd[b-z]' | awk '{print $1}' | sed 's@^@/dev/@g')
  [ -z "${disks[*]}" ] && { echo "no disk found"; return 1; }
  vgcreate "$storage_group" "${disks[*]}"
  lvcreate -n "$storage_vol" -l 100%VG "$storage_group"
  mkfs.ext4 "$storage_dev"
  mount "$storage_dev" "$MINIO_STORAGE"
  cat <<EOF >> /etc/fstab
$storage_dev $MINIO_STORAGE ext4 defaults 0 0
EOF
}

_install_and_run_minio()
{
  local play_id; play_id="$(_get_play_id)"
  local minio; minio="/usr/local/bin/minio"
  local minio_user; minio_user="minio"

  curl https://dl.min.io/server/minio/release/linux-amd64/minio -o "$minio"
  chmod +x "$minio"

   cat <<EOF > /etc/systemd/system/minio.service
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=$minio

[Service]
WorkingDirectory=/usr/local/

User=$minio_user
Group=$minio_user

EnvironmentFile=/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"\${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"

ExecStart=/usr/local/bin/minio server \$MINIO_OPTS \$MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target

EOF

  # set MINIO_STORAGE permissions
  useradd "$minio_user"
  chown "$minio_user":"$minio_user" "$MINIO_STORAGE"

  cat <<EOF > /etc/default/minio
MINIO_ACCESS_KEY=$play_id
MINIO_SECRET_KEY=$play_id
MINIO_VOLUMES=$MINIO_STORAGE
MINIO_OPTS="--address 0.0.0.0:9000"
EOF
  
  unset HTTP_PROXY
  unset HTTPS_PROXY
  unset http_server
  unset https_server

  systemctl daemon-reload
  systemctl enable --now minio
}

