#!/usr/bin/env bash

setup_dependencies()
{
  yum -y clean all
  yum -y install tmux inotify-tools vim nc
  yum -y install iptables-services && systemctl enable --now iptables
  timedatectl set-timezone "$AZCLOUD_APPS_TIMEZONE"
  setup_firewall_and_selinux '5353:udp' && _setup_avahi_centos
}

stage_finished()
{
  local stage; stage="$1"; shift
  local info; info=("$@")

  [ -d "$AZCLOUD_APPS_STAGES" ] || mkdir -p "$AZCLOUD_APPS_STAGES"

  echo "${info[*]}" > "$AZCLOUD_APPS_STAGES"/"$stage"
}

stage_info()
{ 
  echo "$*" >&2
}

_setup_avahi_centos()
{
  local hostname; hostname="$(hostname -s)"
  local play_id; play_id="$(get_play_id)"

  yum -y install avahi avahi-tools

  mv /etc/avahi/{avahi-daemon.conf,avahi-daemon.conf.orig}
  cat <<EOF > /etc/avahi/avahi-daemon.conf
[server]
host-name=${hostname}-${play_id}
use-ipv4=yes
use-ipv6=no
deny-interfaces=docker0
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
publish-hinfo=no
publish-workstation=yes

[reflector]

[rlimits]
EOF
  systemctl enable --now avahi-daemon
}

