#!/usr/bin/env bash

install_dependencies()
{
  yum -y clean all
  yum -y install tmux inotify-tools vim nc
  yum -y install iptables-services && systemctl enable --now iptables
}

stage_finished()
{
  local stage; stage="$1"; shift
  local info; info=("$@")

  [ -d "$AZCLOUD_APPS_STAGES" ] || mkdir -p "$AZCLOUD_APPS_STAGES"

  echo "${info[*]}" > "$AZCLOUD_APPS_STAGES"/"$stage"
}

_stage_info()
{ 
  echo "$*" >&2
}

_install_avahi_centos()
{
  yum -y install avahi-daemon avahi-tools

  mv /etc/avahi/{avahi-daemon.conf,avahi-daemon.conf.orig}
  cat <<'EOF' > /etc/avahi/avahi-daemon.conf
[server]
use-ipv4=yes
use-ipv6=no
deny-interfaces=docker0
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
publish-hinfo=no
publish-workstation=yes

[reflector]

[rlimits]
EOF
  systemctl restart avahi-daemon

  cat <<'EOF' > /etc/systemd/system/avahi-alias@.service
[Unit]
Description=Publish %I as alias for %H.local via mdns
Wants=avahi-daemon.service

[Service]
Type=simple
ExecStart=/bin/bash -c "/usr/bin/avahi-publish -a -R %I $(avahi-resolve -4 -n %H.local | cut -f 2)"

[Install]
WantedBy=multi-user.target
EOF
  local short; short="$(hostname -s)"; short="${short%%-*}"
  systemctl enable --now avahi-alias@"$short".local.service
}

