#!/usr/bin/env bash

_setup_app_storage()
{
  local storage_vol; storage_vol="$1"; shift
  local storage_group; storage_group="${storage_vol}_storage"
  local storage_dev; storage_dev="/dev/${storage_group}/${storage_vol}"

  [ -z "$AZCLOUD_APPS_STORAGE" ] && fatal "MINIO_STORAGE not defined"

  mkdir -p "$AZCLOUD_APPS_STORAGE"

  while IFS='' read -r a; do disks+=("$a"); done < <(lsblk | grep 'sd[b-z]' | awk '{print $1}' | sed 's@^@/dev/@g')
  [ -z "${disks[*]}" ] && { echo "no disk found"; return 1; }
  vgcreate "$storage_group" "${disks[*]}"
  lvcreate -n "$storage_vol" -l 100%VG "$storage_group"
  mkfs.ext4 "$storage_dev"
  mount "$storage_dev" "$AZCLOUD_APPS_STORAGE"
  cat <<EOF >> /etc/fstab
$storage_dev $AZCLOUD_APPS_STORAGE ext4 defaults 0 0
EOF
}


