#!/usr/bin/env bash
#
# INCLUDE: docker

azapps_auth_keycloak()
{
  PROXY="$(get_proxy)"
  export PROXY
  set_proxy
 
  setup_firewall_and_selinux '443:tcp' 'selinux:permissive' \
    && stage_finished setup_firewall_and_selinux
  azapps_docker \
    && stage_finished setup_and_install_docker
  _install_and_setup_keycloak \
    && stage_finished install_and_setup_keycloak
}

