#!/usr/bin/env bash

_get_master_address()
{
  node_to_address "$(get_first_node)"
}

_get_slave_address()
{
  node_to_address "$(for a in $(get_play_nodes); do echo "$a"; done | sort -V | sed -n 2p)"
}

_am_i_kube_master_node()
{
  master_address="$(_get_master_address)"
  local my_address; my_address="$(get_my_address)"
  local exitcode; exitcode=1

  if [ "$my_address" == "$master_address" ]; then
    exitcode=0
  fi
  return ${exitcode}
}

_get_join_cert_digest()
{
  openssl x509 -pubkey -in "$AZCLOUD_APPS_KUBE_CA_CRT" \
    | openssl rsa -pubin -outform der 2>/dev/null \
    | openssl dgst -sha256 -hex \
    | sed 's/^.* //'
}

_get_join_token()
{
  kubeadm token list \
    | awk '{print $1}' \
    | tail -n1
}

_get_join_command()
{
  kubeadm token create --print-join-command 2>/dev/null
}

_get_cluster_size()
{
  kubectl get nodes | grep -wo Ready | wc -l
}

