#!/usr/bin/env bash

azapps_kubernetes_cluster()
{
  AZCLOUD_APPS_STORAGE="/var/lib/docker"
  export AZCLOUD_APPS_STORAGE

  PROXY="$(get_proxy)"
  export PROXY
  set_proxy

  NET="$(_get_default_network)"
  
  setup_firewall_and_selinux '6443:tcp,2379:tcp,2380:tcp,10250:tcp,10251:tcp,10252:tcp,10255:tcp' 'selinux:permissive' "$NET" \
    && stage_finished setup_firewall_and_selinux
  update_host_file \
    && stage_finished update_host_file

  if ! _am_i_kube_master_node; then
    setup_app_storage 'docker' \
      && stage_finished setup_app_storage 
  fi

  install_and_setup_kube \
    && stage_finished install_and_setup_kube

  if _am_i_kube_master_node; then
    setup_kube_master_node
  fi
}
  
