#!/usr/bin/env bash

_get_haproxy_address()
{
  local address
  address="$(vmtoolsd --cmd "info-get guestinfo.appdata" | base64 -d | jq -r .apps.config.haproxy)"
  [ -z "$address" ] && fatal "Could not get haproxy address"
  echo "$address"
}

_get_db_pass()
{
  local db_pass;
  db_pass="$(vmtoolsd --cmd "info-get guestinfo.appdata" | base64 -d | jq -r .apps.config.dbpass)"
  [[ $db_pass == "null" ]] && db_pass="$(_get_play_id)"
  echo "$db_pass"
}

