#!/usr/bin/env bash

_get_haproxy_address()
{
  local address;
  address="$(get_app_config | jq -r '.apps.config.haproxy[0]')"
  [ -z "$address" ] && fatal "Could not get haproxy address from apps.config.haproxy"
  echo "$address"
}

_is_it_haproxy()
{
  local node; node="$1"; shift
  local address; address="$(node_to_address "$node")"
  local haproxy_address; haproxy_address="$(_get_haproxy_address)"
  local haproxy; haproxy=1
  if [ "$haproxy_address" == "$address" ]; then
    haproxy=0
  fi
  return $haproxy
}

_am_i_haproxy()
{
  _is_it_haproxy "$(hostname -s)"
}

_install_and_setup_haproxy()
{
  local my_address; my_address="$(get_my_address)"
  local address

  yum -y install haproxy keepalived
  mv /etc/haproxy/{haproxy.cfg,haproxy.cfg.orig}

  cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    user haproxy
    group haproxy

defaults
    log global
    retries 2
    timeout connect 3000
    timeout server 5000
    timeout client 5000

listen galera-cluster
    bind $my_address:3306
    mode tcp
    option mysql-check user haproxy_check
    balance roundrobin
EOF
  while IFS='' read -r node; do
    address="$(node_to_address "$node")"
    if [ "$address" != "$my_address" ]; then
      cat <<EOF >> /etc/haproxy/haproxy.cfg
    server $node $address:3306 check
EOF
    fi
  done <<< "$(get_play_nodes)"

  unset_proxy
  systemctl enable --now haproxy
}
