#!/usr/bin/env bash

_setup_firewall_and_selinux_nfs4()
{
  if systemctl is-active firewalld | grep -q active; then
    firewall-cmd --permanent --zone=public --add-service=nfs
    firewall-cmd --reload
  elif command -v iptables >& /dev/null; then
    iptables -I INPUT -p tcp --dport 2049 -m comment --comment 'added by azcloud-apps' -m state --state NEW -j ACCEPT
   fi

   # set domain to permissive mode
   semanage permissive -a nfsd_t
}

_setup_nfs4_storage()
{
  local storage_vol; storage_vol="nfs4"
  local storage_group; storage_group="${storage_vol}_storage"
  local storage_dev; storage_dev="/dev/${storage_group}/${storage_vol}"

  [ -z "$NFS_STORAGE" ] && fatal "NFS_STORAGE not defined"

  mkdir -p "$NFS_STORAGE"

  while IFS='' read -r a; do disks+=("$a"); done < <(lsblk | grep 'sd[b-z]' | awk '{print $1}' | sed 's@^@/dev/@g')
  [ -z "${disks[*]}" ] && { echo "no disk found"; return 1; }
  vgcreate "$storage_group" "${disks[*]}"
  lvcreate -n "$storage_vol" -l 100%VG "$storage_group"
  mkfs.ext4 "$storage_dev"
  mount "$storage_dev" "$NFS_STORAGE"
  cat <<EOF >> /etc/fstab
$storage_dev $NFS_STORAGE ext4 defaults 0 0
EOF
}

_install_and_setup_nfs4()
{
  yum -y install nfs-utils

  mkdir -p "$NFS_STORAGE"/share
  chmod -R 755 "$NFS_STORAGE"/share
  chown nfsnobody:nfsnobody "$NFS_STORAGE"/share

  cat <<EOF > /etc/exports.d/azapps.exports
$NFS_STORAGE/share *(rw,sync,no_root_squash,insecure)
EOF
  systemctl enable --now nfs-server
}
