#!/usr/bin/env bash

azapps_databases_mariadb()
{

  AZCLOUD_APPS_STORAGE="/var/lib/mysql"
  export AZCLOUD_APPS_STORAGE

  DB_PASS="$(_get_db_args)"
  export DB_PASS

  PROXY="$(get_proxy)"
  export PROXY

  set_proxy

  setup_app_storage 'mariadb' \
    && stage_finished setup_app_storage
  setup_firewall_and_selinux '3306:tcp' 'mysqld_t:permissive' \
    && stage_finished firewall_and_selinux_setup
  _install_and_setup_mariadb \
    && stage_finished install_and_setup_mariadb
  _finish 
}
