#!/usr/bin/env bash

_set_proxy()
{
  export http_proxy="$HTTP_PROXY"
  export https_proxy="$HTTPS_PROXY"
  export HTTP_PROXY="$HTTP_PROXY"
  export HTTPS_PROXY="$HTTPS_PROXY"
}

_unset_proxy()
{
  unset http_proxy
  unset https_proxy
  unset HTTP_PROXY
  unset HTTPS_PROXY
}

_get_play_id()
{
  local play_id
  play_id="$(hostname -s)"
  play_id="${play_id#*-}"
  play_id="${play_id%%-*}"
  echo "$play_id"
}

_get_db_args()
{
  local apps_args db_pass
  apps_args=$(vmtoolsd --cmd "info-get guestinfo.appdata" | base64 -d)
  db_pass="$(jq -r .apps.config.dbpass <<< "$apps_args")"
  [[ $db_pass == "null" ]] && db_pass="$(_get_play_id)"
  echo "$db_pass"
}


