#!/usr/bin/env bash

azapps_databases_mariadb()
{
  export HTTP_PROXY="$PROXY"
  export HTTPS_PROXY="$PROXY"
  export http_proxy="$PROXY"
  export https_proxy="$PROXY"

  AZCLOUD_APPS_STORAGE="/var/lib/mysql"
  export AZCLOUD_APPS_STORAGE

  DB_PASS="$(_get_db_args)"
  export DB_PASS

  _setup_app_storage 'mariadb' \
    && _stage_finished setup_app_storage
  _setup_firewall_and_selinux '3306:tcp' 'mysqld_t:permissive' \
    && _stage_finished firewall_and_selinux_setup
  _install_and_setup_mariadb \
    && _stage_finished install_and_setup_mariadb
  _finish 
}
