#!/usr/bin/env bash

azapps_databases_mariadb()
{
  export HTTP_PROXY="$PROXY"
  export HTTPS_PROXY="$PROXY"
  export http_proxy="$PROXY"
  export https_proxy="$PROXY"

  DB_PASS="$(_get_db_args)"
  export DB_PASS

  _setup_firewall_and_selinux \
    && _stage_finished firewall_and_selinux_setup
  _install_and_setup_mariadb \
    && _stage_finished install_and_setup_mariadb
  _finish 
}
