#!/usr/bin/env bash

_setup_firewall_and_selinux()
{
  
  iptables -I INPUT -p tcp --dport 3306 -m comment --comment "added by AzCloudApps"
  sed -i '/^SELINUX=/s/enforcing/permissive/g' /etc/selinux/config
  setenforce 0
}

_install_and_setup_mariadb()
{
  yum -y install mariadb mariadb-server expect

  local mysql_root_password="$1"; shift
  local mysql_curr_password=""

  systemctl enable --now mariadb

  secure_mysql=$(expect -c "
set timeout 1
spawn mysql_secure_installation
expect \"Enter current password for root (enter for none):\"
send \"$mysql_curr_password\r\"
expect \"Set root password?*\"
send \"y\r\"
expect \"New password*\"
send \"$mysql_root_password\r\"
expect \"Re-enter new password*\"
send \"$mysql_root_password\r\"
expect \"Remove anonymous users?\"
send \"y\r\"
expect \"Disallow root login remotely?\"
send \"n\r\"
expect \"Remove test database and access to it?\"
send \"y\r\"
expect \"Reload privilege tables now?\"
send \"y\r\"
expect eof
")

echo "$secure_mysql"
}

_finish()
{
  cat <<EOF
##################################
 AzCloudApp info:
 APP MariaDB has been installed
 DBPASS: "$1"
##################################
EOF
}
