#!/usr/bin/env bash

_get_coordinator_address()
{
  (
    for a in $(_get_nodes_addresses); do
      echo "$a"
    done
  ) | sort -V | head -n1
}

_am_i_coordinator()
{
  local coordinator_address; coordinator_address="$(_get_coordinator_address)"
  local my_address; my_address="$(hostname -i)"
  local exitcode; exitcode=1

  if [ "$my_address" == "$coordinator_address" ]; then
    exitcode=0
  fi
  return ${exitcode}
}
