#!/usr/bin/env bash

export HTTP_PROXY="$PROXY"
export HTTPS_PROXY="$PROXY"
export http_proxy="$PROXY"
export https_proxy="$PROXY"

_setup_firewall_and_selinux()
{
  # set selinux to permissiv
  setenforce 0
  sed -i '/^SELINUX=enforcing/s/enforcing/permissive/g' /etc/selinux/config
}

_setup_docker_repo()
{
  :
}

_install_docker()
{
  local docker_url; docker_url="https://get.docker.com/"
  curl -fsSL "$docker_url" | sh
}

_install_docker_compose()
{
  local docker_compose_bin
  local docker_compose_url
  docker_compose_url="https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)"
  docker_compose_bin="/usr/local/bin/docker-compose"

  curl -L "$docker_compose_url" -o "$docker_compose_bin"
  chmod +x "$docker_compose_url"
  ln -s "$docker_compose_bin" "${docker_compose_bin/local\//}"
}

_setup_users_to_use_docker()
{
  for user in $(cut -d: -f1,3 /etc/passwd | sort -n -t: -k2,2); do 
    if [ "${user##*:}" -ge 1000 ]; then
      usermod -aG docker "${user%%:*}"
    fi
  done
}

_start_docker()
{
  systemctl enable --now docker
}

azapps_docker_single()
{
  _setup_firewall_and_selinux
  _setup_docker_repo
  _install_docker
  _install_docker_compose
  _setup_users_to_use_docker
  _start_docker
}

