#!/usr/bin/env bash

get_distribution_name()
{
  if command -v lsb_release &>/dev/null; then
    lsb_release -si | tr '[:upper:]' '[:lower:]'
  else
    (
      unset NAME
      for f in /etc/os-release /usr/lib/os-release; do
        [[ -e ${f} ]] || continue
        # shellcheck disable=SC1090
        source "${f}"
        [[ -n ${NAME} ]] && echo "${NAME%% *}" | tr '[:upper:]' '[:lower:]'
        break
      done
    )
  fi
}

setup_dependencies()
{
  setup_dependencies_"$AZCLOUD_APPS_DISTR"
}

setup_dependencies_centos()
{
  yum -y clean all
  yum -y install tmux inotify-tools vim nmap
  yum -y install iptables-services && systemctl enable --now iptables
  timedatectl set-timezone "$AZCLOUD_APPS_TIMEZONE"

  # avahi disable for now
  # because of bug in avahi-browse
  #setup_firewall_and_selinux '5353:udp' && _setup_avahi_centos
}

setup_dependencies_ubuntu()
{

  _services=(
			 "apt-daily"
			 "apt-daily-upgrade"
			)

  for _service in "${_services[@]}"; do
    systemctl stop "${_service}".timer
    systemctl disable "${_service}".timer
    systemctl mask "${_service}".service
  done
  systemctl daemon-reload

  export DEBIAN_FRONTEND=noninteractive
  apt-get -y update
  apt-get -y install nmap inotify-tools tmux vim netcat
  timedatectl set-timezone "$AZCLOUD_APPS_TIMEZONE"

  # avahi disable for now
  # because of bug in avahi-browse
  #setup_firewall_and_selinux '5353:udp' && _setup_avahi_centos
}

stage_finished()
{
  local stage; stage="$1"; shift
  local info; info=("$@")

  [ -d "$AZCLOUD_APPS_STAGES" ] || mkdir -p "$AZCLOUD_APPS_STAGES"

  echo "${info[*]}" > "$AZCLOUD_APPS_STAGES"/"$stage"
}

stage_info()
{ 
  echo "$*" >&2
}

_setup_avahi_centos()
{
  local hostname; hostname="$(hostname -s)"
  local play_id; play_id="$(get_play_id)"

  yum -y install avahi avahi-tools

  mv /etc/avahi/{avahi-daemon.conf,avahi-daemon.conf.orig}
  cat <<EOF > /etc/avahi/avahi-daemon.conf
[server]
host-name=${hostname}-${play_id}
use-ipv4=yes
use-ipv6=no
deny-interfaces=docker0
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
publish-hinfo=no
publish-workstation=yes

[reflector]

[rlimits]
EOF
  systemctl enable --now avahi-daemon
}

