#!/usr/bin/env bash

setup_firewall_and_selinux()
{
  local fw_rules; fw_rules="$1"; shift
  local sl_rules; sl_rules="$1"; shift
  local nt_rules; nt_rules="$1"; shift
  local port proto
  local action domain

  [ -n "$fw_rules" ] && IFS=, read -ra fw_rules_arr <<< "$fw_rules"
  [ -n "$sl_rules" ] && IFS=, read -ra sl_rules_arr <<< "$sl_rules"
  [ -n "$nt_rules" ] && IFS=, read -ra nt_rules_arr <<< "$nt_rules"

  for rule in ${fw_rules_arr[*]}; do
    port="${rule%%:*}"
    proto="${rule##*:}"
    iptables -I INPUT \
     -p "$proto" --dport "$port" \
     -m comment --comment 'added by azcloud-apps' \
     -m state --state NEW -j ACCEPT
  done

  for rule in ${nt_rules_arr[*]}; do
    net="${rule}"
    [ -z "$net" ] && continue
    iptables -I INPUT \
      -s "$net" \
      -m comment --comment 'added by azcloud-apps' \
      -m state --state NEW -j ACCEPT
  done
  service iptables save

  for rule in ${sl_rules_arr[*]}; do
    domain="${rule%%:*}"
    action="${rule##*:}"
    if [ "$domain" = selinux ]; then
      setenforce 0
      sed -i '/^SELINUX=enforcing/s/enforcing/permissive/g' /etc/selinux/config
      continue
    fi
    semanage "$action" -a "$domain"
  done

  # setup sshd to accept password
  sed -i '/PasswordAuthentication/s/no/yes/g' /etc/ssh/sshd_config
  systemctl restart sshd
}
    
   
